In [1]:
import numpy  as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[1]

2

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(3,)


In [7]:
print(a)

[1 2 3]


In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 1)

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [16]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.eye((3, 4))

TypeError: 'tuple' object cannot be interpreted as an integer

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
d = np.eye(3)

In [21]:
d.prod(np.ones((3, 3)))

TypeError: only integer scalar arrays can be converted to a scalar index

In [22]:
np.random

<module 'numpy.random' from '/Users/jinoo/miniconda3/lib/python3.7/site-packages/numpy/random/__init__.py'>

In [24]:
np.random.random((2,2))

array([[0.31175352, 0.48165022],
       [0.32166245, 0.74326117]])

In [25]:
np.random.binomial()

TypeError: binomial() takes at least 2 positional arguments (0 given)

In [28]:
a = np.array([[x*y for y in range(1, 5)] for x in range(1, 4)])

In [29]:
a[1, :]

array([2, 4, 6, 8])

In [30]:
a

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [31]:
a[1:2, :]

array([[2, 4, 6, 8]])

In [32]:
a[:, 1]

array([2, 4, 6])

In [33]:
a[:, 1:2]

array([[2],
       [4],
       [6]])

In [34]:
np.arange(3)

array([0, 1, 2])

In [35]:
np.arange((2, 3))

TypeError: arange: scalar arguments expected instead of a tuple.

In [36]:
np.arange(1, 4)

array([1, 2, 3])

In [41]:
a =  np.arange(1, 13).reshape((4, 3)).reshape((12,)).reshape((4,3))

In [42]:
b = np.array([0, 2, 0, 1])

In [44]:
a[np.arange(4), b]

array([ 1,  6,  7, 11])

In [45]:
a[np.arange(4), b] += 10

In [46]:
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

In [47]:
a > 5

array([[ True, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [48]:
bool_index = a > 5

In [50]:
a[bool_index]

array([11, 16, 17,  8,  9, 10, 21, 12])

In [51]:
a.dtype

dtype('int64')

In [52]:
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

In [53]:
x = np.array([1.0, 2.0])

In [54]:
x.dtype

dtype('float64')

In [55]:
y  = np.array([1.0, 3])

In [56]:
y.dtype

dtype('float64')

In [57]:
np.add(x, y)

array([2., 5.])

In [58]:
x+y

array([2., 5.])

In [59]:
x-y

array([ 0., -1.])

In [60]:
np.subtract(x, y)

array([ 0., -1.])

In [61]:
np.multiply(x, y)

array([1., 6.])

In [62]:
np.divide(x, y)

array([1.        , 0.66666667])

In [63]:
x/y

array([1.        , 0.66666667])

In [64]:
x
y

array([1., 3.])

In [65]:
x

array([1., 2.])

In [66]:
np.sqrt(x)

array([1.        , 1.41421356])

In [67]:
np.square(x)

array([1., 4.])

In [69]:
x = np.array([[1, 2], [3,4]])
y=  np.array([[5, 6], [7,8]])

In [70]:
v = np.array([9, 10])
w = np.array([11, 12])

In [71]:
v.dot(w)

219

In [72]:
w.dot(v)

219

In [73]:
np.dot(v,w)

219

In [74]:
x.dot(v)

array([29, 67])

In [75]:
v.dot(x)

array([39, 58])

In [76]:
x

array([[1, 2],
       [3, 4]])

In [77]:
v

array([ 9, 10])

In [78]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [79]:
y

array([[5, 6],
       [7, 8]])

In [80]:
y.dot(x)

array([[23, 34],
       [31, 46]])

In [81]:
x = np.array([[1,2], [3,4]])

In [82]:
np.sum(x)

10

In [83]:
np.sum(x, axis=0)

array([4, 6])

In [84]:
np.sum(x, axis=1)

array([3, 7])

In [85]:
x.T

array([[1, 3],
       [2, 4]])

In [86]:
x.transpose()

array([[1, 3],
       [2, 4]])

In [87]:
x

array([[1, 2],
       [3, 4]])

In [88]:
v = np.array([1,2,3])

In [89]:
v.T

array([1, 2, 3])

In [90]:
v.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [91]:
np.sum(x, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [92]:
test = np.array([[[1,2], [3,4]], [[5,6], [7,8]], [[9, 10], [11, 12]]])

In [93]:
test

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [94]:
test.ndim

3

In [95]:
test.axis

AttributeError: 'numpy.ndarray' object has no attribute 'axis'

In [96]:
test.shape

(3, 2, 2)

In [97]:
test.sum()

78

In [98]:
np.sum(test)

78

In [99]:
np.sum(test, axis=0)

array([[15, 18],
       [21, 24]])

In [100]:
np.sum(test, axis=1)

array([[ 4,  6],
       [12, 14],
       [20, 22]])

In [101]:
np.sum(test, axis=2)

array([[ 3,  7],
       [11, 15],
       [19, 23]])

In [102]:
test = np.array([[[1,2, 3], [3,4,5]], [[5,6,7], [7,8,9]], [[9, 10,11], [11, 12,13]]])

In [103]:
test.shape

(3, 2, 3)

In [104]:
np.sum(test, axis=2)

array([[ 6, 12],
       [18, 24],
       [30, 36]])

In [105]:
test

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [11, 12, 13]]])

In [106]:
np.sum(test, axis=1)

array([[ 4,  6,  8],
       [12, 14, 16],
       [20, 22, 24]])

In [107]:
np.sum(test, axis=0)

array([[15, 18, 21],
       [21, 24, 27]])

In [111]:
alpha = np.array([[2, 5], [7, 9]])
beta = np.array([[6, 3, 10], [5, 4, 3]])

In [109]:
alpha

array([[2, 5],
       [7, 9]])

In [112]:
beta

array([[ 6,  3, 10],
       [ 5,  4,  3]])

In [113]:
alpha.dot(beta)

array([[37, 26, 35],
       [87, 57, 97]])

In [114]:
beta.dot(alpha)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [115]:
alpha[0]

array([2, 5])

In [116]:
alpha[0].dot(beta[:, 0])

37

In [117]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

In [118]:
y

array([[-6917529027641081856,  5764616293274335589,                    6],
       [                   0,  8675445200430039040,  7290884029659899243],
       [ 3270512069467267383,  7365694559254569781,  3831779538122190131],
       [ 3835206741632825702,  8386112019185807668,     1697620100543349]])

In [119]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [120]:
np.empty_like([[1,1],[2,2]])

array([[-6917529027641081856, -6917529027641081856],
       [                   6,                    0]])

In [121]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [122]:
x.len

AttributeError: 'numpy.ndarray' object has no attribute 'len'

In [123]:
x.size

12

In [124]:
x.length

AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [125]:
len(x)

4

In [126]:
len(x[0])

3

In [127]:
for i in range(len(x)):
    y[i, :] = x[i, :] + v

In [128]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [129]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [130]:
v

array([1, 0, 1])

In [131]:
np.tile(v, 4)

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1])

In [132]:
np.tile(v, (4, 3))np.tile(v, (4, 3))

array([[1, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1]])

In [133]:
np.tile(v, (4, 1))

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [134]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [135]:
x + np.tile(v, (4,1))

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [136]:
x + v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [137]:
v = np.array([1,2,3])
w = np.array([4,5])

In [138]:
np.reshape(v, (3,1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [139]:
np.reshape(w, (2,1)) * v

array([[ 4,  8, 12],
       [ 5, 10, 15]])

In [140]:
np.reshape(v, (3,1))

array([[1],
       [2],
       [3]])

In [141]:
x = np.array([[1,2,3], [4,5,6]])

In [142]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
v

array([1, 2, 3])

In [144]:
x+v

array([[2, 4, 6],
       [5, 7, 9]])

In [145]:
np.reshape(x, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [146]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [147]:
w

array([4, 5])

In [148]:
x.T + w

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [149]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [150]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
w.T

array([4, 5])

In [152]:
x + np.reshape(w, (2,1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [154]:
np.reshape(w, (2,1))

array([[4],
       [5]])